default: &default
  aws_access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: <%= ENV['S3_MEDIA_BUCKET_TRAINING_PPSDMK'] %>
  region: <%= ENV['S3_REGION_TRAINING_PPSDMK'] %>
  acl: 'private'
  max_expiration_time: 30
  max_file_size: 500
  large_max_file_size: 2048
  cache_control: 'public; max-age=31104000'
  s3_url: 's3.amazonaws.com'
  asset_host: <%= ENV['MEDIA_HOST_NAME_TRAINING_PPSDMK'] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
